logging:
  level: INFO
  loggers:
    gojoego: DEBUG
    org.hibernate.SQL: TRACE

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  user: username
  password: password
  url: jdbc:postgresql://localhost/minesweeperdb
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: create

  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 4

  # the maximum number of connections to keep open
  maxSize: 16

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false